"""JSON-RPC client for the Mintlayer wallet daemon.

Mirrors go-sdk/wallet (Go package ``wallet``). Default ports: 3034 (mainnet),
13034 (testnet).

    from mintlayer.wallet import Client, SendParams, Amount

    c = Client("http://127.0.0.1:3034")
    c.open_wallet("/path/to/wallet.dat")
    result = c.address_send(SendParams(
        account=0, address="mtc1q...", amount=Amount(atoms="100000000000"),
    ))
    print(result.tx_id)
"""

from __future__ import annotations

from mintlayer._jsonrpc import JSONRPCError

from .client import Client, RPCError
from .orders import coin_filter, token_filter
from .types import (
    AccountInfo,
    ActiveOrder,
    AddressWithUsage,
    Amount,
    Balance,
    BestBlock,
    ChangeAuthorityParams,
    ComposedTx,
    ComposeParams,
    ConcludeOrderParams,
    CreateDelegationParams,
    CreateDelegationResult,
    CreateOrderParams,
    CreatePoolParams,
    CreateWalletParams,
    CreateWalletResult,
    CurrencyFilter,
    DecommissionParams,
    DelegateParams,
    DelegationInfo,
    FeesBreakdown,
    FillOrderParams,
    FreezeOrderParams,
    FreezeParams,
    IssueNFTParams,
    IssueTokenParams,
    IssueTokenResult,
    ListOrdersParams,
    LockSupplyParams,
    MintParams,
    MnemonicResult,
    NFTMetadata,
    OrderCreated,
    OrderState,
    Outpoint,
    OutpointSourceID,
    OutputValue,
    OwnedPool,
    OwnOrder,
    RecoverWalletParams,
    RevealPublicKeyResult,
    SendParams,
    SendResult,
    SignedTx,
    StakingStatus,
    SubmitResult,
    SweepParams,
    Timestamp,
    TokenMetadata,
    TokenSendParams,
    TokenSupply,
    TxInspection,
    TxOptions,
    TxStats,
    UnfreezeParams,
    UnmintParams,
    UTXOSpendParams,
    WalletInfo,
    WalletTx,
    WithdrawParams,
)

__all__ = [
    "Client",
    "RPCError",
    "JSONRPCError",
    "coin_filter",
    "token_filter",
    "Amount",
    "AccountInfo",
    "ActiveOrder",
    "AddressWithUsage",
    "Balance",
    "BestBlock",
    "ChangeAuthorityParams",
    "ComposeParams",
    "ComposedTx",
    "ConcludeOrderParams",
    "CreateDelegationParams",
    "CreateDelegationResult",
    "CreateOrderParams",
    "CreatePoolParams",
    "CreateWalletParams",
    "CreateWalletResult",
    "CurrencyFilter",
    "DelegateParams",
    "DelegationInfo",
    "DecommissionParams",
    "FillOrderParams",
    "FreezeOrderParams",
    "FreezeParams",
    "FeesBreakdown",
    "IssueNFTParams",
    "IssueTokenParams",
    "IssueTokenResult",
    "ListOrdersParams",
    "LockSupplyParams",
    "MintParams",
    "MnemonicResult",
    "NFTMetadata",
    "OrderCreated",
    "OrderState",
    "Outpoint",
    "OutpointSourceID",
    "OutputValue",
    "OwnedPool",
    "OwnOrder",
    "RecoverWalletParams",
    "RevealPublicKeyResult",
    "SendParams",
    "SendResult",
    "SignedTx",
    "StakingStatus",
    "SubmitResult",
    "SweepParams",
    "Timestamp",
    "TokenMetadata",
    "TokenSendParams",
    "TokenSupply",
    "TxInspection",
    "TxOptions",
    "TxStats",
    "UTXOSpendParams",
    "UnfreezeParams",
    "UnmintParams",
    "WalletInfo",
    "WalletTx",
    "WithdrawParams",
]
